//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsoleEvents.VelibServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibServiceReference.IVelibService", CallbackContract=typeof(ClientConsoleEvents.VelibServiceReference.IVelibServiceCallback))]
    public interface IVelibService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStationData", ReplyAction="http://tempuri.org/IVelibService/GetStationDataResponse")]
        void GetStationData(string stationName, string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStationData", ReplyAction="http://tempuri.org/IVelibService/GetStationDataResponse")]
        System.Threading.Tasks.Task GetStationDataAsync(string stationName, string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SubscribeCalculatedEvent", ReplyAction="http://tempuri.org/IVelibService/SubscribeCalculatedEventResponse")]
        void SubscribeCalculatedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SubscribeCalculatedEvent", ReplyAction="http://tempuri.org/IVelibService/SubscribeCalculatedEventResponse")]
        System.Threading.Tasks.Task SubscribeCalculatedEventAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SubscribeCalculationFinishedEvent", ReplyAction="http://tempuri.org/IVelibService/SubscribeCalculationFinishedEventResponse")]
        void SubscribeCalculationFinishedEvent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/SubscribeCalculationFinishedEvent", ReplyAction="http://tempuri.org/IVelibService/SubscribeCalculationFinishedEventResponse")]
        System.Threading.Tasks.Task SubscribeCalculationFinishedEventAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibService/Calculated")]
        void Calculated(string city, string station, string nbVelib);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IVelibService/CalculationFinished")]
        void CalculationFinished();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : ClientConsoleEvents.VelibServiceReference.IVelibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.DuplexClientBase<ClientConsoleEvents.VelibServiceReference.IVelibService>, ClientConsoleEvents.VelibServiceReference.IVelibService {
        
        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetStationData(string stationName, string cityName) {
            base.Channel.GetStationData(stationName, cityName);
        }
        
        public System.Threading.Tasks.Task GetStationDataAsync(string stationName, string cityName) {
            return base.Channel.GetStationDataAsync(stationName, cityName);
        }
        
        public void SubscribeCalculatedEvent() {
            base.Channel.SubscribeCalculatedEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeCalculatedEventAsync() {
            return base.Channel.SubscribeCalculatedEventAsync();
        }
        
        public void SubscribeCalculationFinishedEvent() {
            base.Channel.SubscribeCalculationFinishedEvent();
        }
        
        public System.Threading.Tasks.Task SubscribeCalculationFinishedEventAsync() {
            return base.Channel.SubscribeCalculationFinishedEventAsync();
        }
    }
}
